In [1]:
import numpy as np

In [4]:
ary1 = np.array([1,2,3])
ary2 = np.array([[1,2,3],[4,5,6]])

print(ary1)
print(ary2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [6]:
ary3 = np.array([11, True, "joke"])
print(ary3)

['11' 'True' 'joke']


In [7]:
zero1 = np.zeros((3,))
zero2 = np.zeros((2,3))

print(zero1)
print(zero2)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
identity1 = np.eye(1)
identity2 = np.eye(2)

print(identity1)
print(identity2)

[[1.]]
[[1. 0.]
 [0. 1.]]


In [9]:
one1 = np.ones((3,))
one2 = np.ones((2,3))

print(one1)
print(one2)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
const1 = np.full((3,),7)
const2 = np.full((2,3),7)

print(const1)
print(const2)

[7 7 7]
[[7 7 7]
 [7 7 7]]


In [12]:
ary1 = np.array([[1,2,3],[4,5,6]])
print(type(ary1),ary1.ndim,ary1.shape,ary1.dtype)

<class 'numpy.ndarray'> 2 (2, 3) int64


In [16]:
sample1 = np.arange(0.,5.,0.2)
print(sample1)

np.random.shuffle(sample1)
print(sample1)

sample1 = sample1.reshape(5,5)
print(sample1)

sample1 = sample1.astype("unicode")
print(sample1)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8]
[0.2 4.  0.8 4.4 3.  4.8 3.6 1.4 1.2 2.2 2.4 0.  2.8 4.2 3.8 0.6 4.6 1.6
 3.2 1.8 2.  2.6 0.4 3.4 1. ]
[[0.2 4.  0.8 4.4 3. ]
 [4.8 3.6 1.4 1.2 2.2]
 [2.4 0.  2.8 4.2 3.8]
 [0.6 4.6 1.6 3.2 1.8]
 [2.  2.6 0.4 3.4 1. ]]
[['0.2' '4.0' '0.8' '4.4' '3.0']
 ['4.800000000000001' '3.6' '1.4000000000000001' '1.2000000000000002'
  '2.2']
 ['2.4000000000000004' '0.0' '2.8000000000000003' '4.2'
  '3.8000000000000003']
 ['0.6000000000000001' '4.6000000000000005' '1.6' '3.2' '1.8']
 ['2.0' '2.6' '0.4' '3.4000000000000004' '1.0']]


In [18]:
sample1 = np.linspace(0. ,5. ,5)
print(sample1)

sample2 = np.logspace(0. ,5. ,5)
print(sample2)

[0.   1.25 2.5  3.75 5.  ]
[1.00000000e+00 1.77827941e+01 3.16227766e+02 5.62341325e+03
 1.00000000e+05]


In [19]:
sample2 = np.random.randint(1,7,size=15)
print(sample2)

sample3 = np.random.rand(2,3)
print(sample3)

[1 2 4 2 1 4 4 5 6 4 2 1 5 5 3]
[[0.93062391 0.35534618 0.16474299]
 [0.97994984 0.612718   0.41773011]]


In [20]:
normal1 = np.random.randn(3,5)
print(normal1)

normal2 = np.random.normal(10,2,size=(3,5))
print(normal2)

[[ 0.26210671  0.00552843 -1.08104125  0.85043803 -0.21515501]
 [-1.22710698  0.663252    2.32250823 -1.78692285  0.26644312]
 [-0.52617062 -0.16145605 -0.52373852 -0.00741308  0.15334751]]
[[ 8.66105084 12.26269657 10.13914529 10.04120949 12.8115634 ]
 [ 9.01406797  6.36201685 13.26559104  9.22483723  7.57193208]
 [13.11441393 10.00729626  7.41506249 10.60076018  9.25727948]]


In [23]:
X1 = np.array([1, 2, 3])
X2 = np.array([20, 36, 40])
features = np.concatenate((X1,X2)).reshape(2,3).T

print(features)

[[ 1 20]
 [ 2 36]
 [ 3 40]]
