# 環境設定

In [ ]:
# 引入必要的套件
import numpy as np

# 建立陣列

## 建立一般陣列

In [ ]:
# 建立一維陣列
ary1 = np.array([1, 2, 3])
print(ary1)

# 建立二維陣列
ary2 = np.array([[1, 2, 3], [4, 5, 6]])
print(ary2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
# 於 NumPy 陣列內，建立不同資料型態的元素
ary3 = np.array([15, "Apple", True])   #通通變字串
print(ary3)

['15' 'Apple' 'True']


## 建立特殊陣列

In [ ]:
# 建立一維「零陣列」
zero1 = np.zeros((3, ))
print(zero1)

# 建立二維「零陣列」
zero2 = np.zeros((2, 3))
print(zero2)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 建立一維「單位陣列」
identity1 = np.eye(1)
print(identity1)

# 建立二維「單位陣列」
identity2 = np.eye(2)
print(identity2)

In [ ]:
# 建立全為 1 的一維「常數陣列」
one1 = np.ones((3, ))
print(one1)

# 建立全為 1 的二維「常數陣列」
one2 = np.ones((2, 3))
print(one2)

# 建立全為特定數字（如：7）的一維「常數陣列」
const1 = np.full((3, ), 7)
print(const1)

# 建立全為特定數字（如：7）的二維「常數陣列」
const2 = np.full((2, 3), 7)
print(const2)

# 讀寫陣列元素

In [ ]:
# 讀取陣列元素
ary1 = np.array([[1, 2, 3], [4, 5, 6]])
print(ary1[0, 0], ary1[1, 2])

1 6


In [ ]:
# 寫入陣列元素
ary1[0, 0] = 100
ary1[1, 2] = 600
print(ary1)

[[100   2   3]
 [  4   5 600]]


# 讀取陣列資訊

In [ ]:
# 產生陣列
ary1 = np.array([[1, 2, 3], [4, 5, 6]])

# 讀取陣列各種資訊
print(type(ary1), ary1.ndim, ary1.shape, ary1.dtype)

<class 'numpy.ndarray'> 2 (2, 3) int64


# 產生「樣本點」

## 產生「線性」樣本點

In [ ]:
# 產生「線性」樣本點
sample1 = np.arange(0., 5., 0.2)
print(sample1)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8]


In [ ]:
# 產生「線性」樣本點 + 洗牌
sample1 = np.arange(0., 5., 0.2)
np.random.shuffle(sample1)
print(sample1)

[4.2 2.  1.2 0.4 1.4 3.4 2.6 4.8 3.6 4.6 2.8 1.8 2.2 2.4 4.  0.2 4.4 3.8
 0.  3.2 0.6 1.6 0.8 1.  3. ]


In [ ]:
# 產生「線性」樣本點 + 更改維度
sample1 = np.arange(0., 5., 0.2)
print(sample1.reshape(5, 5))

[[0.  0.2 0.4 0.6 0.8]
 [1.  1.2 1.4 1.6 1.8]
 [2.  2.2 2.4 2.6 2.8]
 [3.  3.2 3.4 3.6 3.8]
 [4.  4.2 4.4 4.6 4.8]]


In [ ]:
# 產生「線性」樣本點 + 更改資料型態
sample1 = np.arange(0., 5., 0.2)
sample1 = sample1.astype("unicode")
print(sample1)

['0.0' '0.2' '0.4' '0.6000000000000001' '0.8' '1.0' '1.2000000000000002'
 '1.4000000000000001' '1.6' '1.8' '2.0' '2.2' '2.4000000000000004' '2.6'
 '2.8000000000000003' '3.0' '3.2' '3.4000000000000004' '3.6'
 '3.8000000000000003' '4.0' '4.2' '4.4' '4.6000000000000005'
 '4.800000000000001']


## 產生「等差 / 等比」樣本點

In [ ]:
# 產生「等差樣本點」
sample1 = np.linspace(0., 5., 5)
print(sample1)

[0.   1.25 2.5  3.75 5.  ]


In [ ]:
# 產生「等比樣本點」
sample1 = np.logspace(0., 5., 5)
print(sample1)

[1.00000000e+00 1.77827941e+01 3.16227766e+02 5.62341325e+03
 1.00000000e+05]


## 產生「亂數」樣本點

In [ ]:
# 產生「整數亂數」樣本點
sample2 = np.random.randint(1, 7, size=15)
print(sample2)

[5 4 5 5 4 5 1 5 2 5 3 2 1 1 2]


In [ ]:
# 產生「浮點數亂數」樣本點
sample3 = np.random.rand(2, 3)
print(sample3)

[[0.39829844 0.95625387 0.25764681]
 [0.95812284 0.47515785 0.81890058]]


## 產生「常態分佈」樣本點

In [ ]:
# 產生「標準常態分佈」樣本點
normal1 = np.random.randn(3, 5)
print(normal1)

[[ 1.98538567  0.09160739 -0.21597642 -0.55063177  0.96030438]
 [-0.37168587 -1.09823678 -0.66067691  0.77377398 -0.20988392]
 [ 0.57030676 -1.58157595  0.00656876 -1.10629097  0.54246923]]


In [ ]:
# 產生「一般常態分佈」樣本點
normal2 = np.random.normal(10, 2, size=(3, 5))
print(normal2)

[[ 8.06224851 11.71828827  8.78684428  9.32590905  7.79428145]
 [10.60659473  4.46061296  8.98418437  9.35997711 10.30490849]
 [11.35732792  8.91779019 10.99808013 10.35440411 14.31893783]]


# 切片運算（Slicing）

In [ ]:
# 一維陣列切片運算
slice1 = np.random.randint(20, size=20)
print(slice1)
print(slice1[:5])

[ 2  5 11 10  0 14  6  4 19 17 19 17  4 17 10 18  2  5 11 10]
[ 2  5 11 10  0]


In [ ]:
# 二維陣列切片運算
slice2 = np.random.randint(20, size=(5, 5))
print(slice2)
print(slice2[:3, :3])

[[16 13  9  8  6]
 [18  0 18 11 10]
 [17  1 18  7 15]
 [ 7  8 18 15  2]
 [ 1  8 18 11  4]]
[[16 13  9]
 [18  0 18]
 [17  1 18]]


# 統計量的計算

In [ ]:
# 極小、極大、總和、平均、標準差的計算
stat1 = np.arange(1, 11)
print(stat1)

print(stat1.min())
print(stat1.max())
print(stat1.sum())
print(stat1.mean())
print(stat1.std())

[ 1  2  3  4  5  6  7  8  9 10]
1
10
55
5.5
2.8722813232690143


# 陣列轉置（Transpose）

In [ ]:
# 陣列並排合併後轉置
X1 = np.array([1, 2, 3])
X2 = np.array([20, 36, 40])

features = np.concatenate((X1, X2)).reshape(2, 3).T
print(features)

[[ 1 20]
 [ 2 36]
 [ 3 40]]
