###讀入資料並印出

In [65]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/cnchi/datasets/master/Match_Making.csv')

In [66]:
import numpy as np

In [ ]:
print(df)

        ID  Age  Height  Salary Education Matching
0   ID0001   25     179      75   College        N
1   ID0002   33     190      95   College        Y
2   ID0003   28     180      90    Master        Y
3   ID0004   25     178      90    Master        Y
4   ID0005   46     177     500    Master        N
5   ID0006   40     170     350  Bachelor        N
6   ID0007   34     174     100    Master        Y
7   ID0008   36     181     220  Bachelor        N
8   ID0009   35     170     125    Master        Y
9   ID0010   30     180     175  Bachelor        Y
10  ID0011   28     174     150  Bachelor        N
11  ID0012   29     176     180  Bachelor        Y


###切分自、應變數

In [ ]:
x = df.iloc[:, 1:5].values
y = df.iloc[:, 5].values

In [ ]:
x

array([[25, 179, 75, 'College'],
       [33, 190, 95, 'College'],
       [28, 180, 90, 'Master'],
       [25, 178, 90, 'Master'],
       [46, 177, 500, 'Master'],
       [40, 170, 350, 'Bachelor'],
       [34, 174, 100, 'Master'],
       [36, 181, 220, 'Bachelor'],
       [35, 170, 125, 'Master'],
       [30, 180, 175, 'Bachelor'],
       [28, 174, 150, 'Bachelor'],
       [29, 176, 180, 'Bachelor']], dtype=object)

In [ ]:
y

array(['N', 'Y', 'Y', 'Y', 'N', 'N', 'Y', 'N', 'Y', 'Y', 'N', 'Y'],
      dtype=object)

###類別資料數位化

In [ ]:
ary_dummies = pd.get_dummies(x[:, 3]).values
X = np.concatenate((ary_dummies, x[:, 0:3]), axis=1).astype("float64")
X

array([[  0.,   1.,   0.,  25., 179.,  75.],
       [  0.,   1.,   0.,  33., 190.,  95.],
       [  0.,   0.,   1.,  28., 180.,  90.],
       [  0.,   0.,   1.,  25., 178.,  90.],
       [  0.,   0.,   1.,  46., 177., 500.],
       [  1.,   0.,   0.,  40., 170., 350.],
       [  0.,   0.,   1.,  34., 174., 100.],
       [  1.,   0.,   0.,  36., 181., 220.],
       [  0.,   0.,   1.,  35., 170., 125.],
       [  1.,   0.,   0.,  30., 180., 175.],
       [  1.,   0.,   0.,  28., 174., 150.],
       [  1.,   0.,   0.,  29., 176., 180.]])

In [ ]:
from sklearn.preprocessing import LabelEncoder

labelEncoder = LabelEncoder()
Y = labelEncoder.fit_transform(y).astype("float64")
Y

array([0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1.])

###切分訓練、測試集並印出

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [ ]:
print("X_train:\n", X_train)
print("X_test:\n", X_test)
print("Y_train:\n", Y_train)
print("Y_test:\n", Y_test)

X_train:
 [[  1.   0.   0.  28. 174. 150.]
 [  0.   0.   1.  28. 180.  90.]
 [  0.   0.   1.  35. 170. 125.]
 [  0.   1.   0.  33. 190.  95.]
 [  1.   0.   0.  36. 181. 220.]
 [  1.   0.   0.  30. 180. 175.]
 [  0.   0.   1.  25. 178.  90.]
 [  0.   1.   0.  25. 179.  75.]
 [  1.   0.   0.  40. 170. 350.]]
X_test:
 [[  0.   0.   1.  34. 174. 100.]
 [  1.   0.   0.  29. 176. 180.]
 [  0.   0.   1.  46. 177. 500.]]
Y_train:
 [0. 1. 1. 1. 0. 1. 1. 0. 0.]
Y_test:
 [1. 1. 0.]


###特徵縮放並印出

In [ ]:
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler().fit(X_train)
X_train = sc_X.transform(X_train)
X_test = sc_X.transform(X_test)

In [ ]:
X_train

array([[ 1.11803399, -0.53452248, -0.70710678, -0.63375022, -0.68599434,
        -0.02678358],
       [-0.89442719, -0.53452248,  1.41421356, -0.63375022,  0.34299717,
        -0.74994022],
       [-0.89442719, -0.53452248,  1.41421356,  0.79218778, -1.37198868,
        -0.32809885],
       [-0.89442719,  1.87082869, -0.70710678,  0.38477692,  2.05798302,
        -0.68967716],
       [ 1.11803399, -0.53452248, -0.70710678,  0.99589321,  0.51449576,
         0.81689917],
       [ 1.11803399, -0.53452248, -0.70710678, -0.22633937,  0.34299717,
         0.27453169],
       [-0.89442719, -0.53452248,  1.41421356, -1.24486651,  0.        ,
        -0.74994022],
       [-0.89442719,  1.87082869, -0.70710678, -1.24486651,  0.17149859,
        -0.93072938],
       [ 1.11803399, -0.53452248, -0.70710678,  1.81071492, -1.37198868,
         2.38373855]])

In [ ]:
X_test

array([[-0.89442719, -0.53452248,  1.41421356,  0.58848235, -0.68599434,
        -0.62941411],
       [ 1.11803399, -0.53452248, -0.70710678, -0.43004479, -0.34299717,
         0.33479474],
       [-0.89442719, -0.53452248,  1.41421356,  3.03294749, -0.17149859,
         4.19163014]])